### ISSUE TITLE
Temperature & Humidity are rounded instead of showing decimals

### ISSUE THREAD

**Issue by acmaarts** [delid4ve/openhab-3.x-sonoff#3]
Using OH3 and Sonoff Version 2.2r1 I only get rounded temperature values from my Sonoff Zigbee Temperature and Humidity Sensor. Instead of showing 20.2 it's showing 20.0.

The same sensor shows the Humidity rounded as well. If I'll go to "Analyze" on the Humidity sensor it is off by a factor 100. So instead of 34% it's showing 0.34%

I'm completely new to OH so I don't know if it's a configuration or a code issue. Can you help me figure that out?

**Comment by delid4ve** [comment]
Can you test with this please.
https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_v2.4r2.jar

let me know if it’s still an issue

**Comment by TefiLaci** [comment]
I using OH3.0.2 and Sonoff v2.4r2.jar and the situation is the same. Thermo & humidity sensor type: SNZB-02
Thanks for your help in advance!

![kép](https://user-images.githubusercontent.com/83137851/115972375-38912300-a54e-11eb-8fd5-604bf980cc56.png)

**Comment by delid4ve** [comment]
I’ll take a look tomorrow 👍

**Comment by delid4ve** [comment]
Should now be fixed, can you test and let me know.
https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-3.1.0-SNAPSHOT_2.5r1.jar
https://github.com/delid4ve/openhab-sonoff-compiled/blob/main/org.openhab.binding.sonoff-2.5.13-SNAPSHOT_2.4r3.jar

**Comment by TefiLaci** [comment]
Thats working well!
![kép](https://user-images.githubusercontent.com/83137851/116129299-3ce24b00-a6ca-11eb-8134-ad9915652f3e.png)

Thanks!

**Comment by acmaarts** [comment]
@delid4ve I just tried the 2.5r1 version (OH 3.1.0) but it's still not working for me. Do I have to do something to make this work other than replacing the jar?
